### ISSUE TITLE
Add link to phabricator?

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/commons-app.github.io#17]
Although Github is a place that attracts a lot of people, it is also not the central place where the different Wikimedia communities do most of their planing. I am wondering if we should add a link to the Phabricator project as well.

Does the app link to phabricator? There is a risk that we get bug reports twice, but there is also the chance that we draw in people from the Commons community over phabricator. Some people might also feel more comfortable commenting there.

https://phabricator.wikimedia.org/project/profile/1632/

**Comment by misaochan** [comment]
I'm not sure about this... GitHub is far more suited to our workflow than Phabricator I think, especially due to the ease of referring to pull requests on issues, or linking to issues on commits, etc. We already do receive some comments on our Phabricator board. I respond to them there, but whenever action is needed, I still have to create an issue on GitHub for them, which results in duplication.

I would lean towards letting people post there if they want to, but not explicitly encouraging it by linking to it in our app or website. If we do link to it, we should at least state that GitHub is preferable IMO.

**Comment by nicolas-raoul** [comment]
I also support not leading average app users to Phabricator, for fears of duplication, and because Github's issue/commit/PR autolinking is really convenient.
People who are very active in Phabricator will have no trouble finding it anyway.

**Comment by sivaraam** [comment]
Closing this "question" as GitHub seems to be the place to report issues and the [Phabricator project](https://phabricator.wikimedia.org/project/profile/1632/) being referred to in the description has been archived.
